import type { Finding, RuleCopy } from '../types';

type FormatArgs = {
  finding: Finding;
  ruleCopy?: RuleCopy;
  severityLabel: string;
  lang: 'en' | 'ru';
};

function resolveMessage(finding: Finding, ruleCopy?: RuleCopy): string {
  const template = ruleCopy?.message;
  if (!template) return finding.message;
  if (template.includes('{{component}}') && !finding.component) return finding.message;
  return template.replace(/{{\s*component\s*}}/g, finding.component || '');
}

function resolveTitle(finding: Finding, ruleCopy?: RuleCopy): string {
  return ruleCopy?.title || finding.ruleId;
}

function resolveDescription(ruleCopy?: RuleCopy): string {
  return ruleCopy?.description || '';
}

function resolveLocation(finding: Finding): { page: string; component: string } {
  return {
    page: finding.page || '',
    component: finding.component || '',
  };
}

function resolveItemsCount(finding: Finding): number {
  return finding.items?.length || 1;
}

export function formatSlackFinding({ finding, ruleCopy, severityLabel, lang }: FormatArgs): string {
  const title = resolveTitle(finding, ruleCopy);
  const message = resolveMessage(finding, ruleCopy);
  const description = resolveDescription(ruleCopy);
  const { page, component } = resolveLocation(finding);
  const itemsCount = resolveItemsCount(finding);

  if (lang === 'ru') {
    return [
      '🧩 Design Lint — проблема',
      '',
      `*${title}* · ${severityLabel}`,
      message,
      '',
      `_${description}_`,
      '',
      `📍 Где: ${page} / ${component}`,
      `🔎 Элементов: ${itemsCount}`,
    ].join('\n');
  }

  return [
    '🧩 Design Lint — issue',
    '',
    `*${title}* · ${severityLabel}`,
    message,
    '',
    `_${description}_`,
    '',
    `📍 Where: ${page} / ${component}`,
    `🔎 Items: ${itemsCount}`,
  ].join('\n');
}

export function formatJiraFinding({ finding, ruleCopy, severityLabel, lang }: FormatArgs): string {
  const title = resolveTitle(finding, ruleCopy);
  const message = resolveMessage(finding, ruleCopy);
  const description = resolveDescription(ruleCopy);
  const { page, component } = resolveLocation(finding);
  const itemsCount = resolveItemsCount(finding);
  const rationale = ruleCopy?.rationale || '';
  const whenTriggered = ruleCopy?.whenTriggered || '';

  if (lang === 'ru') {
    return [
      `h3. Design Lint: ${title}`,
      '',
      `*Severity:* ${severityLabel}`,
      `*Rule ID:* ${finding.ruleId}`,
      '',
      'h4. Что нашли',
      message,
      '',
      'h4. Описание',
      description,
      '',
      'h4. Где',
      `*Page:* ${page}`,
      `*Component:* ${component}`,
      `*Items:* ${itemsCount}`,
      '',
      'h4. Почему это важно',
      rationale,
      '',
      'h4. Когда срабатывает',
      whenTriggered,
      '',
      '----',
      'Generated by Design Lint (Anatomy)',
    ].join('\n');
  }

  return [
    `h3. Design Lint: ${title}`,
    '',
    `*Severity:* ${severityLabel}`,
    `*Rule ID:* ${finding.ruleId}`,
    '',
    'h4. What we found',
    message,
    '',
    'h4. Description',
    description,
    '',
    'h4. Where',
    `*Page:* ${page}`,
    `*Component:* ${component}`,
    `*Items:* ${itemsCount}`,
    '',
    'h4. Why this matters',
    rationale,
    '',
    'h4. When it triggers',
    whenTriggered,
    '',
    '----',
    'Generated by Design Lint (Anatomy)',
  ].join('\n');
}
